name: Check

on:
  push:
    branches:
      - master
    paths-ignore: 
      - '**.md'
  pull_request:

jobs:
  check:

    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: yandex/clickhouse-server:latest
        ports:
          - 8123:8123

    steps:
      - name: Checkout Metabase Repo
        uses: actions/checkout@v2
        with:
          repository: metabase/metabase
          ref: v1.44.6
      - name: Checkout Driver Repo
        uses: actions/checkout@v2
        with:
          path: modules/drivers/clickhouse
      - name: Prepare JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1182.sh &&
          sudo bash ./linux-install-1.11.1.1182.sh
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
#       - name: Get M2 cache
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.m2
#             ~/.gitlibs
#           key: ${{ runner.os }}-clickhouse-${{ hashFiles('**/deps.edn') }}
      - name: Build ClickHouse driver
        run: |
          sed -i 's#sqlite#clickhouse#g' modules/drivers/deps.edn
          bin/build-driver.sh clickhouse
      - name: Archive driver JAR
        uses: actions/upload-artifact@v2
        with:
          name: clickhouse.metabase-driver.jar
          path: resources/modules/clickhouse.metabase-driver.jar
      - name: Prepare stuff for pulses
        run: yarn build-static-viz
      - name: Run tests
        run:
          DRIVERS=clickhouse clojure -X:dev:drivers:drivers-dev:test
#       - name: Report test results
#         uses: mikepenz/action-junit-report@v2.8.1
#         if: always()
#         with:
#           report_paths: '**/target/junit/*.xml'
#           github_token: ${{ secrets.GITHUB_TOKEN }}
